name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: composer install --prefer-source --no-interaction
  
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: PHP Unit
      run: ./vendor/bin/phpunit
