name: Run PHPUnit

on:
  push:
    branches: [ krc/add-github-actions ]
  pull_request:

jobs:
  run_phpunit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: your-github-token
      GITHUB_CLIENT_ID: your-github-client-id
      GITHUB_CLIENT_SECRET: your-github-client-secret
      GITHUB_URL: http://host/auth/github/callback

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: 7.2
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
    
    - name: Install dependencies
      uses: php-actions/composer@v4
      with:
        composer_version: 1
        args: --prefer-source --no-interaction

    - name: PHP Unit
      run: vendor/bin/phpunit
